name: Publish

on:
  push:
    branches:
      - 'main'

env:
  REGISTRY: harbor.fractalems.com
  REPOSITORY: hmi-v2/web-template-node-service

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    environment: DockerArchiveSecrets
    steps:
      - name: Sanitize branch name
        env:
          BRANCH_NAME: ${{ github.ref_name }}
        run: 'echo "BRANCH_NAME=${BRANCH_NAME//\//-}" >> $GITHUB_ENV'
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          target: production
          tags: ${{ format('{0}/{1}:{2}-{3}', env.REGISTRY, env.REPOSITORY, env.BRANCH_NAME, github.sha) }}
